ALTER PROCEDURE [dbo].[zz_CopyUsers]
(
	@UserName varchar(max), 
	@Password varchar(max) = null, 
	@Email varchar(max) = null, 
	@FirstName varchar(max) = null, 
	@LastName varchar(max)  = null, 
	@MiddleName varchar(max)  = null, 
	@CellPhone varchar(max)  = null, 
	@WorkPhone varchar(max) = null, 
	@HomePhone varchar(max) = null, 
	@DOB datetime  = null, 
	@GUID varchar(max) = null, 
	@DateCreated datetime  = null,  
	@dateedited datetime = null,
	@DateDeleted datetime  = null, 
	@CreatedBy int = null, 
	@IsPublic int = null, 
	@IsDomain bit, 
	@Inactive varchar(max) = null, 
	@ReasonInactive varchar(max) = null, 
	@ChangePassword bit, 
	@Verified varchar(max) = null, 
	@Online varchar(max) = null, 
	@IsDeleted bit = null, 
	@agreed_terms bit = null, 
	@ResponseID int = null, 
	@PreferredLanguage varchar(max) = null, 
	@FailedLoginAttempts int = null, 
	@LastLogin datetime = null, 
	@LastActive datetime = null,
	@GoogleUserName varchar(max) = null, 
	@GooglePassword varchar(max) = null, 
	@ConferencingUserName varchar(max) = null, 
	@ConferencingPassword varchar(max) = null, 
	@IsLocked bit = null, 
	@City varchar(max) = null, 
	@State varchar(max) = null, 
	@ZipCode varchar(max) = null, 
	@Sex varchar(max) = null, 
	@StaffNPI varchar(max) = null, 
	@StaffDEANumber varchar(max) = null, 
	@StaffMedicalLicenseNumber varchar(max) = null, 
	@PagerNumber varchar(max) = null, 
	@FaxNumber varchar(max) = null, 
	@Address1 varchar(max) = null, 
	@Address2 varchar(max) = null, 
	@onepassuserid int = null, 
	@MRN varchar(max) = null, 
	@CellPhoneVerified bit = null, 
	@ExternalID  varchar(max) = null,  
	@ExternalUserID varchar(max) = null, 
	@SourceFacility varchar(max) = null, 
	@SourceFacility_FacilityID int = null, 
	@onepass_agreed_terms bit = null, 
	@XmppUserName varchar(max) = null, 
	@XmppPassword varchar(max) = null, 
	@GroupPager varchar(max) = null, 
	@AnsweringServicePhone varchar(max) = null, 
	@AdditionalLocationPhone varchar(max) = null, 
	@ContactPrefVoiceOnCall varchar(max) = null, 
	@ContactPrefVoiceOffCall varchar(max) = null, 
	@ContactPrefNotificationOnCall varchar(max) = null, 
	@ContactPrefNotificationOffCall varchar(max) = null, 
	@UniquePatientGUID varchar(max) = null, 
	@vCard nvarchar(max) = null, 
	@PracticeAreas  varchar(max) = null,
	@PracticeFacilities varchar(max) = null,  
	@PracticeZipCodes varchar(max) = null, 
	@SSN varchar(max) = null,
	@Race varchar(max) = null, 

@VideoAddress varchar(max) = null, 
@UniqueValue nvarchar(max) = null,
@Photo varchar(max) = null, 
@Country varchar(max) = null, 
@FileServiceKey varchar(max) = null, 
@ExternalAuthUserName varchar(max) = null, 
@VideoType varchar(max) = null, 
@PrimarySpecialty varchar(max) = null
)           
AS 
BEGIN   
set @UserName = REPLACE(@UserName,'@@','''')
set @FirstName = REPLACE(@FirstName,'@@','''')
set @LastName = REPLACE(@LastName,'@@','''')

IF NOT EXISTS(SELECT USERID FROM rz_User WHERE UserName = @UserName)
BEGIN
declare @USERID int
	INSERT INTO dbo.rz_user 
            (username, 
             password, 
             email, 
             firstname, 
             lastname, 
             middlename, 
             cellphone, 
             workphone, 
             homephone, 
             dob, 
             guid, 
             datecreated, 
             dateedited, 
             datedeleted, 
             createdby, 
             ispublic, 
             isdomain, 
             inactive, 
             reasoninactive, 
             changepassword, 
             verified, 
             online, 
             isdeleted, 
             agreed_terms, 
             responseid, 
             preferredlanguage, 
             failedloginattempts, 
             lastlogin, 
             lastactive,
             googleusername, 
             googlepassword, 
             conferencingusername, 
             conferencingpassword, 
             islocked, 
             city, 
             state, 
             zipcode, 
             sex, 
             staffnpi, 
             staffdeanumber, 
             staffmedicallicensenumber, 
             pagernumber, 
             faxnumber, 
             address1, 
             address2, 
             onepassuserid, 
             mrn, 
             cellphoneverified, 
             externalid, 
             externaluserid, 
             sourcefacility, 
             sourcefacility_facilityid, 
             onepass_agreed_terms, 
             xmppusername, 
             xmpppassword, 
             grouppager, 
             answeringservicephone, 
             additionallocationphone, 
             contactprefvoiceoncall, 
             contactprefvoiceoffcall, 
             contactprefnotificationoncall, 
             contactprefnotificationoffcall, 
             uniquepatientguid, 
             vcard, 
             practiceareas, 
             practicefacilities, 
             practicezipcodes,
			 SSN,
			 Race,

VideoAddress,
UniqueValue,
Photo,
Country,
FileServiceKey,
ExternalAuthUserName,
VideoType,
PrimarySpecialty
			 ) 
VALUES      (@UserName, 
             @Password, 
             @Email, 
             @FirstName, 
             @LastName, 
             @MiddleName, 
             @CellPhone, 
             @WorkPhone, 
             @HomePhone, 
             @DOB, 
             @GUID, 
             @DateCreated, 
			 @dateedited, 
             @DateDeleted, 
             @CreatedBy, 
             @IsPublic, 
             @IsDomain, 
             @Inactive, 
             @ReasonInactive, 
             @ChangePassword, 
             @Verified, 
             @Online, 
             @IsDeleted, 
             @agreed_terms, 
             @ResponseID, 
             @PreferredLanguage, 
             @FailedLoginAttempts, 
             @LastLogin, 
             @LastActive, 
             @GoogleUserName, 
             @GooglePassword, 
             @ConferencingUserName, 
             @ConferencingPassword, 
             @IsLocked, 
             @City, 
             @State, 
             @ZipCode, 
             @Sex, 
             @StaffNPI, 
             @StaffDEANumber, 
             @StaffMedicalLicenseNumber, 
             @PagerNumber, 
             @FaxNumber, 
             @Address1, 
             @Address2, 
             @onepassuserid, 
             @MRN, 
             @CellPhoneVerified, 
             @ExternalID, 
             @ExternalUserID, 
             @SourceFacility, 
             @SourceFacility_FacilityID, 
             @onepass_agreed_terms, 
             @XmppUserName, 
             @XmppPassword, 
             @GroupPager, 
             @AnsweringServicePhone, 
             @AdditionalLocationPhone, 
             @ContactPrefVoiceOnCall, 
             @ContactPrefVoiceOffCall, 
             @ContactPrefNotificationOnCall, 
             @ContactPrefNotificationOffCall, 
             @UniquePatientGUID, 
             @vCard, 
             @PracticeAreas, 
             @PracticeFacilities, 
             @PracticeZipCodes, 
             @SSN,
			 @Race,
@VideoAddress,
@UniqueValue,
@Photo,
@Country,
@FileServiceKey,
@ExternalAuthUserName,
@VideoType,
@PrimarySpecialty
)


SELECT @USERID = USERID FROM rz_User WHERE UserName = @UserName
IF NOT EXISTS (SELECT * FROM rz_UserRoles WHERE UserID = @USERID AND ROLE = 2)
BEGIN
	INSERT INTO rz_UserRoles
	(UserID, Role)
	VALUES
	(@USERID, 2)
END
END
select @USERID
END